### ISSUE TITLE
Whatsapp++

### ISSUE THREAD

**Issue by anshgoswami** [Legitgamer264/PPAppsIPARepo#1]
Why can't i see the restore option while installing whatsapp++ (duplicate) ?

**Comment by Legitgamer264** [comment]
I will look into it. Thank you for notifying me

**Comment by Legitgamer264** [comment]
Are you not seeing the "Restore from iCloud" screen?

**Comment by anshgoswami** [comment]
Yes . I'm not getting my backup and so I'm restore button is greyed out . 
I backed it up myself and also I've tried this on 2 phones .

**Comment by anshgoswami** [comment]
So my restore*

**Comment by Legitgamer264** [comment]
is iCloud drive turned on even though it is telling you to turn it on?

**Comment by anshgoswami** [comment]
Yes

**Comment by Legitgamer264** [comment]
I am having that too. I will talk to Unlimapps about it when he gets the free time. I will keep you updated

**Comment by anshgoswami** [comment]
Thank w

**Comment by anshgoswami** [comment]
Thank you *

**Comment by Legitgamer264** [comment]
you're welcome.

**Comment by anshgoswami** [comment]
Also do you know anywhere I could find find VSCO++ I've been finding it for a long while now ?

**Comment by Legitgamer264** [comment]
I do not know where to find that. I wish I did

**Comment by anshgoswami** [comment]
Ok thank you

**Comment by Legitgamer264** [comment]
Update: just got a message from UnlimApps: "iCloud restore won't work on sideloaded because it's server sided"

**Comment by anshgoswami** [comment]
Ok thanks .
That's really sad

**Comment by Legitgamer264** [comment]
Yeah I know. But there is nothing UnlimApps can do about it
